// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Fixtures.Azure.Lro.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubProductProperties
    {
        /// <summary>
        /// Initializes a new instance of the SubProductProperties class.
        /// </summary>
        public SubProductProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubProductProperties class.
        /// </summary>
        /// <param name="provisioningStateValues">Possible values include:
        /// 'Succeeded', 'Failed', 'canceled', 'Accepted', 'Creating',
        /// 'Created', 'Updating', 'Updated', 'Deleting', 'Deleted',
        /// 'OK'</param>
        public SubProductProperties(string provisioningState = default(string), string provisioningStateValues = default(string))
        {
            ProvisioningState = provisioningState;
            ProvisioningStateValues = provisioningStateValues;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "provisioningState")]
        public string ProvisioningState { get; set; }

        /// <summary>
        /// Gets possible values include: 'Succeeded', 'Failed', 'canceled',
        /// 'Accepted', 'Creating', 'Created', 'Updating', 'Updated',
        /// 'Deleting', 'Deleted', 'OK'
        /// </summary>
        [JsonProperty(PropertyName = "provisioningStateValues")]
        public string ProvisioningStateValues { get; private set; }

    }
}
