// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Fixtures.Azure.Lro.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubProduct : SubResource
    {
        /// <summary>
        /// Initializes a new instance of the SubProduct class.
        /// </summary>
        public SubProduct()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubProduct class.
        /// </summary>
        /// <param name="id">Sub Resource Id</param>
        public SubProduct(string id = default(string), SubProductProperties properties = default(SubProductProperties))
            : base(id)
        {
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public SubProductProperties Properties { get; set; }

    }
}
