// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Fixtures.Validation.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for EnumConst.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(EnumConstConverter))]
    public struct EnumConst : System.IEquatable<EnumConst>
    {
        private EnumConst(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly EnumConst ConstantStringAsEnum = "constant_string_as_enum";


        /// <summary>
        /// Underlying value of enum EnumConst
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for EnumConst
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type EnumConst
        /// </summary>
        public bool Equals(EnumConst e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to EnumConst
        /// </summary>
        public static implicit operator EnumConst(string value)
        {
            return new EnumConst(value);
        }

        /// <summary>
        /// Implicit operator to convert EnumConst to string
        /// </summary>
        public static implicit operator string(EnumConst e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum EnumConst
        /// </summary>
        public static bool operator == (EnumConst e1, EnumConst e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum EnumConst
        /// </summary>
        public static bool operator != (EnumConst e1, EnumConst e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for EnumConst
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is EnumConst && Equals((EnumConst)obj);
        }

        /// <summary>
        /// Returns for hashCode EnumConst
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
