// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Fixtures.ModelFlattening.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The product URL.
    /// </summary>
    public partial class ProductUrl : GenericUrl
    {
        /// <summary>
        /// Initializes a new instance of the ProductUrl class.
        /// </summary>
        public ProductUrl()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductUrl class.
        /// </summary>
        /// <param name="genericValue">Generic URL value.</param>
        /// <param name="odatavalue">URL value.</param>
        public ProductUrl(string genericValue = default(string), string odatavalue = default(string))
            : base(genericValue)
        {
            Odatavalue = odatavalue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets URL value.
        /// </summary>
        [JsonProperty(PropertyName = "@odata.value")]
        public string Odatavalue { get; set; }

    }
}
