// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Fixtures.ModelFlattening.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The product documentation.
    /// </summary>
    public partial class SimpleProductProperties
    {
        /// <summary>
        /// Initializes a new instance of the SimpleProductProperties class.
        /// </summary>
        public SimpleProductProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SimpleProductProperties class.
        /// </summary>
        /// <param name="maxProductDisplayName">Display name of
        /// product.</param>
        public SimpleProductProperties(string maxProductDisplayName, ProductUrl maxProductImage = default(ProductUrl))
        {
            MaxProductDisplayName = maxProductDisplayName;
            MaxProductImage = maxProductImage;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for SimpleProductProperties class.
        /// </summary>
        static SimpleProductProperties()
        {
            Capacity = "Large";
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets display name of product.
        /// </summary>
        [JsonProperty(PropertyName = "max_product_display_name")]
        public string MaxProductDisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "max_product_image")]
        public ProductUrl MaxProductImage { get; set; }

        /// <summary>
        /// Capacity of product. For example, 4 people.
        /// </summary>
        [JsonProperty(PropertyName = "max_product_capacity")]
        public static string Capacity { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (MaxProductDisplayName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MaxProductDisplayName");
            }
        }
    }
}
