// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Fixtures.Url.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for UriColor.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(UriColorConverter))]
    public struct UriColor : System.IEquatable<UriColor>
    {
        private UriColor(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly UriColor Redcolor = "red color";

        public static readonly UriColor Greencolor = "green color";

        public static readonly UriColor Bluecolor = "blue color";


        /// <summary>
        /// Underlying value of enum UriColor
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for UriColor
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type UriColor
        /// </summary>
        public bool Equals(UriColor e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to UriColor
        /// </summary>
        public static implicit operator UriColor(string value)
        {
            return new UriColor(value);
        }

        /// <summary>
        /// Implicit operator to convert UriColor to string
        /// </summary>
        public static implicit operator string(UriColor e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum UriColor
        /// </summary>
        public static bool operator == (UriColor e1, UriColor e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum UriColor
        /// </summary>
        public static bool operator != (UriColor e1, UriColor e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for UriColor
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is UriColor && Equals((UriColor)obj);
        }

        /// <summary>
        /// Returns for hashCode UriColor
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
