// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Fixtures.BodyString.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for Colors.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(ColorsConverter))]
    public struct Colors : System.IEquatable<Colors>
    {
        private Colors(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly Colors Redcolor = "red color";

        public static readonly Colors GreenColor = "green-color";

        public static readonly Colors BlueColor = "blue_color";


        /// <summary>
        /// Underlying value of enum Colors
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for Colors
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type Colors
        /// </summary>
        public bool Equals(Colors e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to Colors
        /// </summary>
        public static implicit operator Colors(string value)
        {
            return new Colors(value);
        }

        /// <summary>
        /// Implicit operator to convert Colors to string
        /// </summary>
        public static implicit operator string(Colors e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum Colors
        /// </summary>
        public static bool operator == (Colors e1, Colors e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum Colors
        /// </summary>
        public static bool operator != (Colors e1, Colors e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for Colors
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is Colors && Equals((Colors)obj);
        }

        /// <summary>
        /// Returns for hashCode Colors
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
